export async function getTeams() {
  return {
    teams: [
      { id: 'real-madrid', name: 'Real Madrid', country: 'Espanha', continent: 'Europa' },
      { id: 'barcelona', name: 'FC Barcelona', country: 'Espanha', continent: 'Europa' },
      {
        id: 'atletico-madrid',
        name: 'Atlético de Madrid',
        country: 'Espanha',
        continent: 'Europa',
      },
      {
        id: 'manchester-united',
        name: 'Manchester United',
        country: 'Inglaterra',
        continent: 'Europa',
      },
      {
        id: 'manchester-city',
        name: 'Manchester City',
        country: 'Inglaterra',
        continent: 'Europa',
      },
      { id: 'liverpool', name: 'Liverpool', country: 'Inglaterra', continent: 'Europa' },
      { id: 'chelsea', name: 'Chelsea', country: 'Inglaterra', continent: 'Europa' },
      { id: 'arsenal', name: 'Arsenal', country: 'Inglaterra', continent: 'Europa' },
      { id: 'bayern-munich', name: 'Bayern de Munique', country: 'Alemanha', continent: 'Europa' },
      {
        id: 'borussia-dortmund',
        name: 'Borussia Dortmund',
        country: 'Alemanha',
        continent: 'Europa',
      },
      { id: 'juventus', name: 'Juventus', country: 'Itália', continent: 'Europa' },
      { id: 'inter-milan', name: 'Inter de Milão', country: 'Itália', continent: 'Europa' },
      { id: 'ac-milan', name: 'AC Milan', country: 'Itália', continent: 'Europa' },
      { id: 'psg', name: 'Paris Saint-Germain', country: 'França', continent: 'Europa' },
      {
        id: 'olympique-marseille',
        name: 'Olympique de Marseille',
        country: 'França',
        continent: 'Europa',
      },
      { id: 'ajax', name: 'Ajax', country: 'Países Baixos', continent: 'Europa' },
      { id: 'feyenoord', name: 'Feyenoord', country: 'Países Baixos', continent: 'Europa' },
      { id: 'benfica', name: 'Benfica', country: 'Portugal', continent: 'Europa' },
      { id: 'porto', name: 'FC Porto', country: 'Portugal', continent: 'Europa' },
      { id: 'celtic', name: 'Celtic', country: 'Escócia', continent: 'Europa' },
      { id: 'flamengo', name: 'Flamengo', country: 'Brasil', continent: 'América do Sul' },
      { id: 'corinthians', name: 'Corinthians', country: 'Brasil', continent: 'América do Sul' },
      { id: 'palmeiras', name: 'Palmeiras', country: 'Brasil', continent: 'América do Sul' },
      { id: 'sao-paulo', name: 'São Paulo FC', country: 'Brasil', continent: 'América do Sul' },
      { id: 'santos', name: 'Santos FC', country: 'Brasil', continent: 'América do Sul' },
      { id: 'gremio', name: 'Grêmio', country: 'Brasil', continent: 'América do Sul' },
      {
        id: 'internacional',
        name: 'Internacional',
        country: 'Brasil',
        continent: 'América do Sul',
      },
      { id: 'cruzeiro', name: 'Cruzeiro', country: 'Brasil', continent: 'América do Sul' },
      {
        id: 'atletico-mineiro',
        name: 'Atlético Mineiro',
        country: 'Brasil',
        continent: 'América do Sul',
      },
      { id: 'vasco', name: 'Vasco da Gama', country: 'Brasil', continent: 'América do Sul' },

      {
        id: 'la-galaxy',
        name: 'LA Galaxy',
        country: 'Estados Unidos',
        continent: 'América do Norte',
      },
      {
        id: 'inter-miami',
        name: 'Inter Miami',
        country: 'Estados Unidos',
        continent: 'América do Norte',
      },
      {
        id: 'new-york-city-fc',
        name: 'New York City FC',
        country: 'Estados Unidos',
        continent: 'América do Norte',
      },
      {
        id: 'new-york-red-bulls',
        name: 'New York Red Bulls',
        country: 'Estados Unidos',
        continent: 'América do Norte',
      },
      {
        id: 'seattle-sounders',
        name: 'Seattle Sounders',
        country: 'Estados Unidos',
        continent: 'América do Norte',
      },
      {
        id: 'atlanta-united',
        name: 'Atlanta United',
        country: 'Estados Unidos',
        continent: 'América do Norte',
      },
      {
        id: 'houston-dynamo',
        name: 'Houston Dynamo',
        country: 'Estados Unidos',
        continent: 'América do Norte',
      },

      { id: 'brazil-nt', name: 'Brasil', country: 'Brasil', continent: 'Seleções' },
      { id: 'argentina-nt', name: 'Argentina', country: 'Argentina', continent: 'Seleções' },
      { id: 'germany-nt', name: 'Alemanha', country: 'Alemanha', continent: 'Seleções' },
      { id: 'italy-nt', name: 'Itália', country: 'Itália', continent: 'Seleções' },
      { id: 'france-nt', name: 'França', country: 'França', continent: 'Seleções' },
      { id: 'england-nt', name: 'Inglaterra', country: 'Inglaterra', continent: 'Seleções' },
      { id: 'spain-nt', name: 'Espanha', country: 'Espanha', continent: 'Seleções' },
      { id: 'portugal-nt', name: 'Portugal', country: 'Portugal', continent: 'Seleções' },
      { id: 'uruguay-nt', name: 'Uruguai', country: 'Uruguai', continent: 'Seleções' },
      { id: 'netherlands-nt', name: 'Holanda', country: 'Países Baixos', continent: 'Seleções' },

      { id: 'al-hilal', name: 'Al Hilal', country: 'Arábia Saudita', continent: 'Ásia' },
      { id: 'al-nassr', name: 'Al Nassr', country: 'Arábia Saudita', continent: 'Ásia' },
      { id: 'al-ittihad', name: 'Al Ittihad', country: 'Arábia Saudita', continent: 'Ásia' },
      { id: 'kashima-antlers', name: 'Kashima Antlers', country: 'Japão', continent: 'Ásia' },
      { id: 'gamba-osaka', name: 'Gamba Osaka', country: 'Japão', continent: 'Ásia' },
      {
        id: 'guangzhou-evergrande',
        name: 'Guangzhou Evergrande',
        country: 'China',
        continent: 'Ásia',
      },
      { id: 'shanghai-sipg', name: 'Shanghai Port', country: 'China', continent: 'Ásia' },
      { id: 'persepolis', name: 'Persepolis', country: 'Irã', continent: 'Ásia' },
      { id: 'esteghlal', name: 'Esteghlal', country: 'Irã', continent: 'Ásia' },
      {
        id: 'jeonbuk',
        name: 'Jeonbuk Hyundai Motors',
        country: 'Coreia do Sul',
        continent: 'Ásia',
      },
    ],
  }
}
